name:                myXmonad
version:             0.1.0.0
homepage:            https://github.com/pistachiology/dotfiles
author:              Laoticharoen Nuttapol
maintainer:          im@itua.dev

dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
  - containers
  - text
  - X11
  - ghc

executables:
  xmonad:
    source-dirs:      src
    main:             main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -Wall
    - -O2
    - -fwarn-tabs
